export const GET_PROD_REQUEST = "GET_PROD_REQUEST";
export const GET_PROD_SUCCESS = "GET_PROD_SUCCESS";
export const GET_PROD_FAILURE = "GET_PROD_FAILURE";


export const EDIT_PRODUCT = 'EDIT_PRODUCT';

